; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; 使用本地已下载的 arduino-esp32 框架（避免从官方 CDN 慢速下载）
platform_packages =
    framework-arduinoespressif32 @ C:/.platformio/packages/framework-arduinoespressif32

; ArduinoJson 用于构造/解析 HTTP JSON，版本 7.x
lib_deps =
    bblanchon/ArduinoJson@^7.0.0

; 如果烧录时提示分区不足，可以在这里选择更大的 flash 模式
; board_build.flash_mode = dio

